# Generated by Django 5.2 on 2025-08-05 09:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Naraynpur High School", editable=False, max_length=200
                    ),
                ),
                (
                    "eiin",
                    models.CharField(default="105409", editable=False, max_length=7),
                ),
                (
                    "established_at",
                    models.DateField(default=datetime.date(1980, 1, 1), editable=False),
                ),
                (
                    "location_url",
                    models.URLField(
                        default="https://maps.app.goo.gl/YSq6eubdtMss756a8",
                        editable=False,
                    ),
                ),
                (
                    "location_address",
                    models.CharField(
                        default="Narayan pur, Amjad-Nagar, Chauddagram-3500",
                        max_length=255,
                    ),
                ),
                ("history", models.TextField()),
                ("motto", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("social_links", models.JSONField(blank=True, default=dict, null=True)),
                ("extra", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Institution Profile",
                "verbose_name_plural": "Institution Profile",
            },
        ),
        migrations.CreateModel(
            name="AClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("6", "Class 6"),
                            ("7", "Class 7"),
                            ("8", "Class 8"),
                            ("9", "Class 9"),
                            ("10", "Class 10"),
                        ],
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("room_number", models.CharField(max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(default="105409", max_length=10, unique=True),
                ),
                ("motto", models.CharField(blank=True, max_length=120)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="schools/"),
                ),
                ("location_address", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_subject", models.CharField(max_length=120, unique=True)),
                ("subject_code", models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20, unique=True)),
                (
                    "is_graduated",
                    models.BooleanField(
                        default=False,
                        help_text="Mark this batch as graduated or archived.",
                    ),
                ),
                (
                    "graduation_year",
                    models.CharField(
                        choices=[
                            ("1980", "1980"),
                            ("1981", "1981"),
                            ("1982", "1982"),
                            ("1983", "1983"),
                            ("1984", "1984"),
                            ("1985", "1985"),
                            ("1986", "1986"),
                            ("1987", "1987"),
                            ("1988", "1988"),
                            ("1989", "1989"),
                            ("1990", "1990"),
                            ("1991", "1991"),
                            ("1992", "1992"),
                            ("1993", "1993"),
                            ("1994", "1994"),
                            ("1995", "1995"),
                            ("1996", "1996"),
                            ("1997", "1997"),
                            ("1998", "1998"),
                            ("1999", "1999"),
                            ("2000", "2000"),
                            ("2001", "2001"),
                            ("2002", "2002"),
                            ("2003", "2003"),
                            ("2004", "2004"),
                            ("2005", "2005"),
                            ("2006", "2006"),
                            ("2007", "2007"),
                            ("2008", "2008"),
                            ("2009", "2009"),
                            ("2010", "2010"),
                            ("2011", "2011"),
                            ("2012", "2012"),
                            ("2013", "2013"),
                            ("2014", "2014"),
                            ("2015", "2015"),
                            ("2016", "2016"),
                            ("2017", "2017"),
                            ("2018", "2018"),
                            ("2019", "2019"),
                            ("2020", "2020"),
                            ("2021", "2021"),
                            ("2022", "2022"),
                            ("2023", "2023"),
                            ("2024", "2024"),
                            ("2025", "2025"),
                            ("2026", "2026"),
                            ("2027", "2027"),
                            ("2028", "2028"),
                            ("2029", "2029"),
                            ("2030", "2030"),
                        ],
                        default="2020",
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nphs_school.aclass",
                    ),
                ),
            ],
        ),
    ]
