# Generated by Django 5.2 on 2025-08-01 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nphs_school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="established_at",
            field=models.DateField(default=datetime.date(1980, 1, 1), editable=False),
        ),
        migrations.AlterField(
            model_name="about",
            name="location_address",
            field=models.CharField(
                default="Narayan pur, Amjad-Nagar, Chauddagram-3500", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="location_url",
            field=models.URLField(
                default="https://maps.app.goo.gl/YSq6eubdtMss756a8", editable=False
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="code",
            field=models.CharField(default="105409", max_length=10, unique=True),
        ),
    ]
