# Generated by Django 5.2 on 2025-08-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nphs_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='label',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
