# Generated by Django 5.2 on 2025-08-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nphs_school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by_headmaster", models.BooleanField(default=False)),
            ],
        ),
    ]
