# Generated by Django 5.2 on 2025-08-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nphs_school', '0002_alter_batch_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aclass',
            name='Subject',
        ),
        migrations.AddField(
            model_name='aclass',
            name='group_subjects',
            field=models.ManyToManyField(
                blank=True,
                related_name='group_classes',
                to='nphs_school.subject',
            ),
        ),
        migrations.AddField(
            model_name='aclass',
            name='main_subjects',
            field=models.ManyToManyField(
                blank=True,
                related_name='main_classes',
                to='nphs_school.subject',
            ),
        ),
        migrations.AddField(
            model_name='aclass',
            name='religional_subjects',
            field=models.ManyToManyField(
                blank=True,
                related_name='religional_classes',
                to='nphs_school.subject',
            ),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(
                choices=[
                    ('compulsory', 'Compulsory'),
                    ('religious', 'Religious'),
                    ('group', 'Group'),
                    ('optional', 'Optional'),
                ],
                default='compulsory',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='aclass',
            name='name',
            field=models.CharField(
                choices=[
                    ('6', 'Class 6'),
                    ('7', 'Class 7'),
                    ('8', 'Class 8'),
                    ('9_science', 'Class 9 Science'),
                    ('10_science', 'Class 10 Science'),
                    ('9_business', 'Class 9 Business'),
                    ('10_business', 'Class 10 Business'),
                    ('9_humanities', 'Class 9 Humanities'),
                    ('10_humanities', 'Class 10 Humanities'),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='aclass',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
    ]
