# Generated by Django 5.2 on 2025-08-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'nphs_school',
            '0003_remove_aclass_subject_aclass_group_subjects_and_more',
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name='aclass',
            old_name='main_subjects',
            new_name='compulsory',
        ),
        migrations.RenameField(
            model_name='aclass',
            old_name='religional_subjects',
            new_name='religious',
        ),
        migrations.AddField(
            model_name='aclass',
            name='extra',
            field=models.ManyToManyField(
                blank=True, related_name='extra', to='nphs_school.subject'
            ),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(
                choices=[
                    ('compulsory', 'Compulsory'),
                    ('religious', 'Religious'),
                    ('group', 'Group'),
                    ('group_optional', 'Group_Optional'),
                    ('optional', 'Optional'),
                    ('extra', 'Extra'),
                ],
                default='compulsory',
                max_length=20,
            ),
        ),
    ]
