# Generated by Django 5.2 on 2025-08-10 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'nphs_school',
            '0004_rename_main_subjects_aclass_compulsory_and_more',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={
                'ordering': ['-notice_for_date', '-created_at'],
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_for_date',
            field=models.DateField(
                db_index=True,
                default=datetime.date.today,
                help_text='The date when the notice needs to be published.',
            ),
        ),
        migrations.AddField(
            model_name='notice',
            name='slug',
            field=models.SlugField(
                blank=True,
                default='notice of narayan pur high school',
                max_length=300,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='notice',
            name='approved_by_headmaster',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='notice',
            constraint=models.UniqueConstraint(
                fields=('title', 'notice_for_date'),
                name='unique_notice_per_date',
            ),
        ),
    ]
