# Generated by Django 5.2 on 2025-08-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nphs_school', '0005_alter_notice_options_notice_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
