# Generated by Django 5.2 on 2025-08-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nphs_school', '0006_alter_notice_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'exam_title',
                    models.CharField(
                        choices=[
                            ('midterm', 'Midterm'),
                            ('final', 'Final'),
                            ('test', 'Test'),
                        ],
                        max_length=50,
                    ),
                ),
                ('starting_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
