# Generated by Django 5.2 on 2025-08-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nphs_school', '0007_exam'),
        ('results', '0003_exam_alter_result_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
