# Generated by Django 5.2 on 2025-08-15 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nphs_school', '0008_delete_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='written_by',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='notices_written',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='notice',
            name='approved_by_headmaster',
            field=models.BooleanField(
                db_index=True, default=False, editable=False
            ),
        ),
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(
                blank=True, editable=False, max_length=300, unique=True
            ),
        ),
    ]
