# Generated by Django 5.2 on 2025-08-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nphs_school', '0009_notice_approved_at_notice_written_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='written_by',
        ),
    ]
