# Generated by Django 5.2 on 2025-08-21 16:17

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nphs_school', '0010_remove_notice_written_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='current_class',
        ),
        migrations.AddField(
            model_name='aclass',
            name='batch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='nphs_school.batch',
            ),
        ),
        migrations.AlterField(
            model_name='about',
            name='eiin',
            field=models.CharField(default='105000', max_length=7),
        ),
        migrations.AlterField(
            model_name='about',
            name='established_at',
            field=models.DateField(default=datetime.date(1980, 1, 1)),
        ),
        migrations.AlterField(
            model_name='about',
            name='location_url',
            field=models.URLField(
                default='https://maps.app.goo.gl/YSq6eubdtMss756a8'
            ),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(default=' High School', max_length=200),
        ),
    ]
