# Generated by Django 5.2 on 2025-08-23 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_account_headmasteraccount_teacher_and_more'),
        (
            'nphs_school',
            '0011_remove_batch_current_class_aclass_batch_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'day',
                    models.CharField(
                        choices=[
                            ('MON', 'Monday'),
                            ('TUE', 'Tuesday'),
                            ('WED', 'Wednesday'),
                            ('THU', 'Thursday'),
                            ('FRI', 'Friday'),
                            ('SAT', 'Saturday'),
                            ('SUN', 'Sunday'),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    'slot',
                    models.CharField(
                        choices=[
                            ('1', '10:00 AM - 10:45 AM'),
                            ('2', '10:45 AM - 11:30 AM'),
                            ('3', '11:30 AM - 12:15 PM'),
                            ('4', '12:15 PM - 01:00 PM'),
                            ('5', '01:00 PM - 02:00 PM'),
                            ('6', '02:00 PM - 02:40 PM'),
                            ('7', '02:40 PM - 03:20 PM'),
                            ('8', '03:20 PM - 04:00 PM'),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    'aclass',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='routines',
                        to='nphs_school.aclass',
                    ),
                ),
                (
                    'subject',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='nphs_school.subject',
                    ),
                ),
                (
                    'teacher',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='accounts.teacheraccount',
                    ),
                ),
            ],
            options={
                'ordering': ['aclass', 'day', 'slot'],
                'unique_together': {('aclass', 'day', 'slot')},
            },
        ),
    ]
