# Generated by Django 5.2 on 2025-08-24 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nphs_school', '0014_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='aclass',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='nphs_school.aclass',
            ),
        ),
    ]
