# Generated by Django 5.2 on 2025-08-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'nphs_school',
            '0016_alter_routine_options_alter_routine_unique_together_and_more',  # noqa: E501
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='slot',
            field=models.CharField(
                choices=[
                    ('1', '10:00 AM - 10:45 AM'),
                    ('2', '10:45 AM - 11:30 AM'),
                    ('3', '11:30 AM - 12:15 PM'),
                    ('4', '12:15 PM - 01:00 PM'),
                    ('5', '01:00 PM - 02:00 PM'),
                    ('6', '02:00 PM - 02:40 PM'),
                    ('7', '02:40 PM - 03:20 PM'),
                    ('8', '03:20 PM - 04:00 PM'),
                ],
                max_length=2,
            ),
        ),
    ]
