# Generated by Django 5.2.5 on 2025-09-01 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_account_headmasteraccount_teacher_and_more'),
        ('nphs_school', '0017_alter_routine_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('message', models.CharField(max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'message_of',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='accounts.teacheraccount',
                    ),
                ),
            ],
        ),
    ]
