# Generated by Django 5.2.5 on 2026-01-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nphs_school', '0018_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='aclass',
            name='grade',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aclass',
            name='group',
            field=models.CharField(
                blank=True,
                choices=[
                    ('science', 'Science'),
                    ('business', 'Business'),
                    ('humanities', 'Humanities'),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
