# Generated by Django 5.2 on 2025-08-07 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')],
                        max_length=7,
                    ),
                ),
                ('amount', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                (
                    'after_transaction_balance',
                    models.IntegerField(default=0, editable=False),
                ),
                (
                    'fund',
                    models.ForeignKey(
                        default=1,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='transactions',
                        to='fund.fund',
                    ),
                ),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
