# Generated by Django 5.2 on 2025-08-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fundtransaction",
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.AlterField(
            model_name="fundtransaction",
            name="fund",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="fund.fund",
            ),
        ),
    ]
