# Generated by Django 5.2 on 2025-08-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundtransaction",
            name="after_transaction_balance",
            field=models.IntegerField(default=0),
        ),
    ]
