# Generated by Django 5.2 on 2025-08-10 07:26

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransaction',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name='fundtransaction',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
