# Generated by Django 5.2 on 2025-08-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0002_alter_fundtransaction_options_and_more"),
        ("nphs_school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="school",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funds",
                to="nphs_school.school",
            ),
        ),
        migrations.AlterField(
            model_name="fundtransaction",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
