# Generated by Django 5.2 on 2025-08-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0003_alter_fund_school_alter_fundtransaction_amount"),
        ("nphs_school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="school",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funds",
                to="nphs_school.school",
            ),
        ),
        migrations.AlterField(
            model_name="fundtransaction",
            name="fund",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="fund.fund",
            ),
        ),
    ]
