# Generated by Django 5.2 on 2025-08-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0004_alter_fundtransaction_after_transaction_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundtransaction",
            name="after_transaction_balance",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
