# Generated by Django 5.2 on 2025-08-07 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nphs_school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('mobile', models.CharField(max_length=14)),
                ('date_of_birth', models.DateField()),
                (
                    'image',
                    models.ImageField(
                        blank=True, null=True, upload_to='Accounts/'
                    ),
                ),
                (
                    'religion',
                    models.CharField(
                        choices=[
                            ('islam', 'Islam'),
                            ('hindu', 'Hindu'),
                            ('buddhist', 'Buddhist'),
                            ('christian', 'Christian'),
                        ],
                        default='islam',
                        max_length=10,
                    ),
                ),
                (
                    'joining_date',
                    models.DateField(
                        help_text='when he/she joined the school'
                    ),
                ),
                ('address', models.TextField()),
                (
                    'last_educational_institute',
                    models.CharField(max_length=120),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='TeacherAccount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_class_teacher', models.BooleanField(default=False)),
                (
                    'account',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='teacher_profile',
                        to='accounts.account',
                    ),
                ),
                (
                    'base_subject',
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='nphs_school.subject',
                    ),
                ),
                (
                    'class_teacher_of',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='class_teacher',
                        to='nphs_school.aclass',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='HeadMasterAccount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('appointed_date', models.DateField()),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='headmaster_profile',
                        to='accounts.teacheraccount',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeHelpersAccount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('designation', models.CharField(max_length=120)),
                (
                    'account',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='office_roles',
                        to='accounts.account',
                    ),
                ),
            ],
            options={
                'unique_together': {('account', 'designation')},
            },
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('roll_number', models.PositiveIntegerField(editable=False)),
                (
                    'group',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('science', 'Science'),
                            ('humanities', 'Humanities'),
                            ('business studies', 'Business Studies'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    'account',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='student_profile',
                        to='accounts.account',
                    ),
                ),
                (
                    'batch',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='nphs_school.batch',
                    ),
                ),
            ],
            options={
                'unique_together': {('batch', 'roll_number')},
            },
        ),
    ]
