# Generated by Django 5.2 on 2025-08-09 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('nphs_school', '0002_alter_batch_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'subject_type',
                    models.CharField(
                        choices=[
                            ('compulsory', 'Compulsory'),
                            ('religious', 'Religious'),
                            ('group', 'Group'),
                            ('optional', 'Optional'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='accounts.studentaccount',
                    ),
                ),
                (
                    'subject',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='nphs_school.subject',
                    ),
                ),
            ],
            options={
                'unique_together': {('student', 'subject', 'subject_type')},
            },
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='subjects',
            field=models.ManyToManyField(
                related_name='students',
                through='accounts.StudentSubject',
                to='nphs_school.subject',
            ),
        ),
    ]
