# Generated by Django 5.2 on 2025-08-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentsubject_studentaccount_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(
                choices=[
                    ('male', 'Male'),
                    ('female', 'FEMALE'),
                    ('others', 'OTHERS'),
                ],
                default='male',
                max_length=10,
            ),
        ),
    ]
