# Generated by Django 5.2 on 2025-08-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="full_name",
            field=models.CharField(default="missing", editable=False, max_length=1000),
        ),
    ]
