# Generated by Django 5.2 on 2025-08-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(
                choices=[
                    ('male', 'Male'),
                    ('female', 'Female'),
                    ('others', 'Others'),
                ],
                default='male',
                max_length=10,
            ),
        ),
    ]
