# Generated by Django 5.2 on 2025-08-20 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'designation',
                    models.CharField(
                        choices=[
                            ('secretary', 'Secretary'),
                            ('member_secretary', 'Member Secretary'),
                            ('member', 'Member'),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        blank=True,
                        help_text='Used for all designations except Member Secretary',  # noqa: E501
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='accounts.account',
                    ),
                ),
                (
                    'head_master',
                    models.OneToOneField(
                        blank=True,
                        help_text='Only for Member Secretary',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='accounts.headmasteraccount',
                    ),
                ),
            ],
        ),
    ]
