# Generated by Django 5.2 on 2025-08-21 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_governingbody'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headmasteraccount',
            old_name='account',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='governingbody',
            name='head_master',
        ),
        migrations.AddField(
            model_name='governingbody',
            name='profession',
            field=models.CharField(default='Teacher', max_length=100),
        ),
        migrations.AlterField(
            model_name='governingbody',
            name='account',
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='accounts.account',
            ),
        ),
    ]
