# Generated by Django 5.2.5 on 2026-01-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_account_headmasteraccount_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(
                blank=True,
                choices=[
                    ('student', 'Student'),
                    ('teacher', 'Teacher'),
                    ('headmaster', 'Headmaster'),
                    ('office_staff', 'Office Staff'),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
