# Generated by Django 5.2.5 on 2026-01-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_role'),
        ('nphs_school', '0019_aclass_grade_aclass_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentaccount',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='group',
            field=models.CharField(
                choices=[
                    ('science', 'Science'),
                    ('humanities', 'Humanities'),
                    ('business studies', 'Business Studies'),
                    ('none', 'No Group'),
                ],
                default='none',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='roll_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='studentaccount',
            unique_together={('batch', 'roll_number', 'group')},
        ),
    ]
